services:
    todo_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: todo_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - postgres

    postgres:
        image: postgres
        container_name: todo_postgres
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network
        expose:
            - 5432
        ports:
            - "1234:5432"

    rent_pgadmin:
        image: dpage/pgadmin4
        container_name: todo_pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "8082:80"
        networks:
            - app-network

    web:
        container_name: todo_web
        image: nginx:alpine  # Use the Nginx image
        ports:
            - "8080:80"  # Map port 9000 on the host to port 80 inside the container
        volumes:
            - ./:/var/www  # Mount the Laravel application directory
            - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use our Nginx config
        depends_on:
            - todo_app  # Ensure PHP-FPM is started before Nginx
        networks:
            - app-network  # Connect to the custom network

volumes:
    postgres_data:

networks:
    app-network:
        driver: bridge
